language: python

matrix:
  include:
  - python:
    - 2.6
    - 3.3
    env:
    - WITH_JWT=false
      WITH_HAWK=false
  - python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    env:
    - WITH_JWT=true
      WITH_HAWK=true

before_install:
  - pip install --upgrade pytest

install: "pip install -r requirements-dev.txt"

script: py.test --cov-report term-missing --cov=falcon_auth

after_success:
  - coveralls
